package com.programs;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class RespondToPage
 */
@WebServlet("/Response")
public class RespondToPage extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public RespondToPage() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		//response.getWriter().append("Served at: ").append(request.getContextPath());
		String companyName = request.getParameter("companyName");
		String hostingString = request.getParameter("webServerHosting");
		String designString = request.getParameter("webPageDesign");
		String javaservString = request.getParameter("JavaServlets");
		String peopleString = request.getParameter("people");
		PrintWriter out = response.getWriter();
		out.print("<html><head><title>Response</title></head><style>.footer{\r\n"
				+ "               color: hotpink;\r\n"
				+ "               font-weight: bolder;\r\n"
				+ "               font-size: x-large;\r\n"
				+ "          }</style><body>");
	
		out.print("<h1>Example Form Response</h1><hr><br>");
		out.print("<h3 style=color:green>This Page was generated by a Servlet</h3><br>");
		out.print("The Query string is <br>");
		out.print(request.getQueryString());
		
		out.print("<br> <br> <b>The Values of the parameter sent by the form are:</b> <br><br>");
		out.print("<i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;number of people:"+peopleString+"<br>");
		out.print("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;company name:"+companyName+"<br>");
		out.print("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;hosting:"+hostingString+"<br>");
		out.print("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;design:"+designString+"<br>");
		out.print("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;javadev:"+javaservString+"<br></i>");
		
		
		out.print("<div class=footer>");
		out.print("<br><br> <b> We would love to help your large company to solve its need for </b> <br>");
		out.print("<ul>");
		if(!(hostingString==null)) {
			out.print("<li> Web Hosting </li>");
		}
		if(!(designString==null)) {
			out.print("<li> Web Page Design </li>");
		}
		if(!(javaservString==null)) {
			out.print("<li> Java Servlets and JSP Development </li>");
		}
		
		out.print("</ul>");
		
		out.print("</div></body></html>");
		
		
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}
